### ISSUE TITLE
How to get head data, anywhere

### ISSUE THREAD

**Issue by TheMangoTrain** [unjs/unhead#146]
### Environment

n/a

### Reproduction

n/a

### Describe the bug

When using Unhead to _set_ page title & meta...

What's the recommended way to _get_ the current page title and meta, anywhere in an app (e.g. Nuxt)?

Example use case: Use that data when building custom breadcrumbs, for instance.

**Comment by harlan-zw** [comment]
Hey @TheMangoTrain, thanks for the issue.

Unhead doesn't have the resolved tags until it renders thre DOM, this happens slightly after the Vue mounts, this is for performance reasons so it can debounce any head changes instead of constantly re-checking head state and rendering tags.

The limitation with this is that you won't have access to the tags immediately, saying that you can hook into the tags once they're resolved. You can see this in action here: https://github.com/harlan-zw/nuxt-unhead/blob/main/src/runtime/plugin.ts

Otherwise, I'd actually recommend to just use route meta to to handle this. This is how the Breadcrumb component in Nuxt SEO Kit works, see https://github.com/harlan-zw/nuxt-seo-kit/blob/main/layer/composables/breacrumbs.ts#L42. You can read off of this same route meta data to set the title: https://github.com/harlan-zw/nuxt-seo-kit/blob/main/layer/components/SeoKit.vue#L124.

Will close for now but let me know if any of that isn't clear.

**Comment by TheMangoTrain** [comment]
Hey, that all makes sense! Thx.

Ya, I saw your suggestion of Nuxt SEO Kit for breadcrumbs elsewhere; I may try it on a future project.

In any case, I'm interested in having an isolated breadcrumbs solution and put together something. Was looking at different ways to pass data (store, head, etc) and ultimately it does use route meta. Here's a proposal for it for vueuse: https://github.com/vueuse/vueuse/issues/2989. I haven't glanced inside Nuxt SEO Kit yet.
