### ISSUE TITLE
Automatic add of @ for twitter site on useSeoMeta

### ISSUE THREAD

**Issue by Barbapapazes** [unjs/unhead#309]
### Describe the feature

Environment
Operating System: Linux
Node Version: v20.11.0
Nuxt Version: 3.9.3
CLI Version: 3.10.0
Nitro Version: 2.8.1
Package Manager: pnpm@8.6.12
Builder: -
User Config: -
Runtime Modules: -
Build Modules: -
Reproduction
/

Describe the bug
Hello,

Could be a great addition to automatically add @ to the beginning of the twitter site. Otherwise, a type could alert dev that he should add one.

For reference: [developer.twitter.com/en/docs/twitter-for-websites/cards/guides/getting-started](https://developer.twitter.com/en/docs/twitter-for-websites/cards/guides/getting-started)

Additional context
No response

Logs
No response

### Additional information

- [X] Would you be willing to help implement this feature?

_https://github.com/nuxt/nuxt/issues/25382_

**Comment by harlan-zw** [comment]
I think it's a good idea :)

In terms of implementation though, I think adding an Unhead plugin for this is a bit much. 

If we wanted to solve this in Nuxt a good place to handle it would be in https://github.com/harlan-zw/nuxt-seo-experiments, having it as a standalone plugin then would be fine.

Otherwise, I was already considering working on a development Unhead plugin that would provide warnings when using tags incorrectly, this could be one of the rules.

**Comment by harlan-zw** [comment]
Closing in favour of https://github.com/unjs/unhead/issues/394
